config_inmetrics: 
  uri: https://inm-api-test.herokuapp.com
  post: /empregado/cadastrar
  put: /empregado/alterar/
  delete: /empregado/deletar/
  get: /empregado/list/
  get_all: /empregado/list_all
  username: inmetrics
  password: automacao
